### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sagarsadhu** [otigges/pdf-form-to-html#3]
While I am trying to run the code, I am getting an error at List<FormField> line number 41 in PdfFormAnalyzer.java. and I also understand where to give input to this code. Can you please reply me at the earliest ?

**Comment by otigges** [comment]
Hello @sagarsadhu, what kind of error do you get? Can you paste the error message and stacktrace, please?

**Comment by sagarsadhu** [comment]
In AppServer.java

Multiple markers at this line
	- The method addServlet(String, String) in the type ServletContextHandler is not applicable for the 
	 arguments (Class<ServletContainer>, String)
	- The type javax.servlet.http.HttpServlet cannot be resolved. It is indirectly referenced from 
	 required .class files
	- Line breakpoint:AppServer [line: 20] - main(String[])
	- The type javax.servlet.Servlet cannot be resolved. It is indirectly referenced from required .class files

The method addServlet(String, String) in the type ServletContextHandler is not applicable for the arguments 
 (Class<DefaultServlet>, String)

The method start() is undefined for the type Server

**Comment by sagarsadhu** [comment]
In FormsRessource.java

line 34
Multiple markers at this line
	- Syntax error on token "-", -- 
	 expected
	- pdf cannot be resolved

**Comment by otigges** [comment]
Looks like the project is not setup correctly in the IDE. Does the project build successfully on command line using `mvn install`? Have you activated Maven in your IDE and resolved the dependencies? (see https://maven.apache.org/)

**Comment by sagarsadhu** [comment]
![1](https://user-images.githubusercontent.com/21293079/45609135-3a300b80-ba74-11e8-949f-8b33839f4835.PNG)
![2](https://user-images.githubusercontent.com/21293079/45609137-3ac8a200-ba74-11e8-9402-5bbc1e3e9c74.PNG)
These errors are occurring in FormsRessource.java

**Comment by sagarsadhu** [comment]
![3](https://user-images.githubusercontent.com/21293079/45609174-63e93280-ba74-11e8-882f-748add357c41.PNG)
![4](https://user-images.githubusercontent.com/21293079/45609177-63e93280-ba74-11e8-8584-8b6a7949fca8.PNG)
These errors are occuring in PdfFormAnalyzer.java

I have imported the project as maven project this time still there are still these errors

Please help me

**Comment by otigges** [comment]
Thanks for the screenshots. The compiler settings need to be switched to Java 8 / Java 1.8. See https://stackoverflow.com/questions/24947844/why-wont-eclipse-switch-the-compiler-to-java-8

**Comment by sagarsadhu** [comment]
![5](https://user-images.githubusercontent.com/21293079/45616924-6f495780-ba8e-11e8-9906-2656ae64ab3f.PNG)
Can I give input like /content/abc.pdf ?

**Comment by otigges** [comment]
Yes, if you have a PDF named abc.pdf in the directory "content", then the `id` parameter in the HTTP request should be "abc.pdf".

**Comment by sagarsadhu** [comment]
![capture](https://user-images.githubusercontent.com/21293079/45743559-ee1ecb80-bc19-11e8-8ccf-272e3f45eb47.PNG)
I am still getting error about the package. 
First i opened the project in eclipse as general project from git.
Next, I converted into maven project using configure option. Then i am getting this error. Can you please help me in fixing this

**Comment by otigges** [comment]
As I don't use eclipse I can not understand and reproduce this error. Maybe you can try to find help in an eclipse forum. 

BTW: The purpose of this GitHub project is just to *illustrate* a PDF-2-HTML approach with a java *example*. It is not a library intended for production use.
